// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CallRpcMethod.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;

namespace Rpc.Protocols
{
    /// <summary>Holder for reflection information generated from CallRpcMethod.proto</summary>
    public static partial class CallRpcMethodReflection
    {

        #region Descriptor
        /// <summary>File descriptor for CallRpcMethod.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static CallRpcMethodReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChNDYWxsUnBjTWV0aG9kLnByb3RvEg1ScGMuUHJvdG9jb2xzIiEKDlJwY1Jl",
                  "cXVlc3REYXRhEg8KB1JlcURhdGEYASABKAkiIAoMUnBjUmVwbHlEYXRhEhAK",
                  "CFJlc3BEYXRhGAEgASgJMlUKDkNhbGxScGNTZXJ2aWNlEkMKA1J1bhIdLlJw",
                  "Yy5Qcm90b2NvbHMuUnBjUmVxdWVzdERhdGEaGy5ScGMuUHJvdG9jb2xzLlJw",
                  "Y1JlcGx5RGF0YSIAYgZwcm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rpc.Protocols.RpcRequestData), global::Rpc.Protocols.RpcRequestData.Parser, new[]{ "ReqData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rpc.Protocols.RpcReplyData), global::Rpc.Protocols.RpcReplyData.Parser, new[]{ "RespData" }, null, null, null)
                }));
        }
        #endregion

    }

    #region Messages
    public sealed partial class RpcRequestData : pb::IMessage<RpcRequestData>
    {
        private static readonly pb::MessageParser<RpcRequestData> _parser = new pb::MessageParser<RpcRequestData>(() => new RpcRequestData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<RpcRequestData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Rpc.Protocols.CallRpcMethodReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RpcRequestData()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RpcRequestData(RpcRequestData other) : this()
        {
            reqData_ = other.reqData_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RpcRequestData Clone()
        {
            return new RpcRequestData(this);
        }

        /// <summary>Field number for the "ReqData" field.</summary>
        public const int ReqDataFieldNumber = 1;
        private string reqData_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ReqData
        {
            get { return reqData_; }
            set
            {
                reqData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as RpcRequestData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(RpcRequestData other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (ReqData != other.ReqData) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (ReqData.Length != 0) hash ^= ReqData.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (ReqData.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(ReqData);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (ReqData.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ReqData);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(RpcRequestData other)
        {
            if (other == null)
            {
                return;
            }
            if (other.ReqData.Length != 0)
            {
                ReqData = other.ReqData;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 10:
                        {
                            ReqData = input.ReadString();
                            break;
                        }
                }
            }
        }

    }

    public sealed partial class RpcReplyData : pb::IMessage<RpcReplyData>
    {
        private static readonly pb::MessageParser<RpcReplyData> _parser = new pb::MessageParser<RpcReplyData>(() => new RpcReplyData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<RpcReplyData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Rpc.Protocols.CallRpcMethodReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RpcReplyData()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RpcReplyData(RpcReplyData other) : this()
        {
            respData_ = other.respData_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RpcReplyData Clone()
        {
            return new RpcReplyData(this);
        }

        /// <summary>Field number for the "RespData" field.</summary>
        public const int RespDataFieldNumber = 1;
        private string respData_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string RespData
        {
            get { return respData_; }
            set
            {
                respData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as RpcReplyData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(RpcReplyData other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (RespData != other.RespData) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (RespData.Length != 0) hash ^= RespData.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (RespData.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(RespData);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (RespData.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(RespData);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(RpcReplyData other)
        {
            if (other == null)
            {
                return;
            }
            if (other.RespData.Length != 0)
            {
                RespData = other.RespData;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 10:
                        {
                            RespData = input.ReadString();
                            break;
                        }
                }
            }
        }

    }

    #endregion

}

#endregion Designer generated code
