// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CallRpcMethod.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Rpc.Protocols
{
    public static partial class CallRpcService
    {
        static readonly string __ServiceName = "Rpc.Protocols.CallRpcService";

        static readonly grpc::Marshaller<global::Rpc.Protocols.RpcRequestData> __Marshaller_Rpc_Protocols_RpcRequestData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rpc.Protocols.RpcRequestData.Parser.ParseFrom);
        static readonly grpc::Marshaller<global::Rpc.Protocols.RpcReplyData> __Marshaller_Rpc_Protocols_RpcReplyData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rpc.Protocols.RpcReplyData.Parser.ParseFrom);

        static readonly grpc::Method<global::Rpc.Protocols.RpcRequestData, global::Rpc.Protocols.RpcReplyData> __Method_Run = new grpc::Method<global::Rpc.Protocols.RpcRequestData, global::Rpc.Protocols.RpcReplyData>(
            grpc::MethodType.Unary,
            __ServiceName,
            "Run",
            __Marshaller_Rpc_Protocols_RpcRequestData,
            __Marshaller_Rpc_Protocols_RpcReplyData);

        /// <summary>Service descriptor</summary>
        public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
        {
            get { return global::Rpc.Protocols.CallRpcMethodReflection.Descriptor.Services[0]; }
        }

        /// <summary>Base class for server-side implementations of CallRpcService</summary>
        public abstract partial class CallRpcServiceBase
        {
            public virtual global::System.Threading.Tasks.Task<global::Rpc.Protocols.RpcReplyData> Run(global::Rpc.Protocols.RpcRequestData request, grpc::ServerCallContext context)
            {
                throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
            }

        }

        /// <summary>Client for CallRpcService</summary>
        public partial class CallRpcServiceClient : grpc::ClientBase<CallRpcServiceClient>
        {
            /// <summary>Creates a new client for CallRpcService</summary>
            /// <param name="channel">The channel to use to make remote calls.</param>
            public CallRpcServiceClient(grpc::Channel channel) : base(channel)
            {
            }
            /// <summary>Creates a new client for CallRpcService that uses a custom <c>CallInvoker</c>.</summary>
            /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
            public CallRpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
            {
            }
            /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
            protected CallRpcServiceClient() : base()
            {
            }
            /// <summary>Protected constructor to allow creation of configured clients.</summary>
            /// <param name="configuration">The client configuration.</param>
            protected CallRpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
            {
            }

            public virtual global::Rpc.Protocols.RpcReplyData Run(global::Rpc.Protocols.RpcRequestData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return Run(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            public virtual global::Rpc.Protocols.RpcReplyData Run(global::Rpc.Protocols.RpcRequestData request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_Run, null, options, request);
            }
            public virtual grpc::AsyncUnaryCall<global::Rpc.Protocols.RpcReplyData> RunAsync(global::Rpc.Protocols.RpcRequestData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return RunAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            public virtual grpc::AsyncUnaryCall<global::Rpc.Protocols.RpcReplyData> RunAsync(global::Rpc.Protocols.RpcRequestData request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_Run, null, options, request);
            }
            /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
            protected override CallRpcServiceClient NewInstance(ClientBaseConfiguration configuration)
            {
                return new CallRpcServiceClient(configuration);
            }
        }

        /// <summary>Creates service definition that can be registered with a server</summary>
        /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
        public static grpc::ServerServiceDefinition BindService(CallRpcServiceBase serviceImpl)
        {
            return grpc::ServerServiceDefinition.CreateBuilder()
                .AddMethod(__Method_Run, serviceImpl.Run).Build();
        }

        /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
        /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
        /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
        /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
        public static void BindService(grpc::ServiceBinderBase serviceBinder, CallRpcServiceBase serviceImpl)
        {
            serviceBinder.AddMethod(__Method_Run, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Rpc.Protocols.RpcRequestData, global::Rpc.Protocols.RpcReplyData>(serviceImpl.Run));
        }

    }
}
#endregion
